name: Run Azure Login with OpenID Connect
on: 
  push:
    branches:
      - uat
  
  workflow_dispatch:
    
jobs: 
  build-and-deploy:
    environment: uat
    runs-on: ubuntu-latest
    steps:
    - uses: elstudio/action-install-azure-cli@v1
    - name: 'Az CLI login'
      with:
        inlinescript: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}  
    - name: 'Run Azure CLI commands'
      run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az account show
